In [1]:
# SENTIMENT ANALYSIS ON spam1.csv

In [2]:
import pandas as pd
import numpy as np
import warnings 
warnings.filterwarnings('ignore')
import matplotlib.pyplot as plt

In [3]:
df= pd.read_csv('/Users/anishgulhane/Downloads/datasets after 14 sept/spam1.csv' ,encoding = 'cp1252')

In [4]:
df.shape

(6776, 5)

In [5]:
df.head()

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN


In [6]:
df.tail()

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
6771,spam,This is the 2nd time we have tried 2 contact u...,NaN,NaN,NaN
6772,ham,Will Ì_ b going to esplanade fr home?,NaN,NaN,NaN
6773,ham,"Pity, * was in mood for that. So...any other s...",NaN,NaN,NaN
6774,ham,The guy did some bitching but I acted like i'd...,NaN,NaN,NaN
6775,ham,Rofl. Its true to its name,NaN,NaN,NaN


In [7]:
df.isnull().sum()

v1               0
v2               0
Unnamed: 2    6720
Unnamed: 3    6760
Unnamed: 4    6768
dtype: int64

In [8]:
df = df.iloc[:,[0,1]]

In [9]:
df.head(1)

,v1,v2
0,ham,"Go until jurong point, crazy.. Available only ..."


In [10]:
df = df.rename(columns = {'v1': 'Y','v2': 'X'})

In [11]:
df.head()

,Y,X
0,ham,"Go until jurong point, crazy.. Available only ..."
1,ham,Ok lar... Joking wif u oni...
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...
3,ham,U dun say so early hor... U c already then say...
4,ham,"Nah I don't think he goes to usf, he lives aro..."


In [12]:
df.Y.value_counts()

Y
ham     5854
spam     922
Name: count, dtype: int64

In [13]:
df.Y = df.Y.replace({'ham':0,'spam':1})

In [14]:
import nltk #  natural language tool kit (library used in NLP)
from nltk.corpus import stopwords

In [15]:

nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/anishgulhane/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [16]:
stopwords.words('english')

['a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 'her',
 'here',
 'hers',
 'herself',
 "he's",
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 'if',
 "i'll",
 "i'm",
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 "i've",
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'on

In [17]:
len(stopwords.words('english'))

198

In [18]:
import string 
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [19]:
# we are yet to remove the stopwords

In [20]:
df['X'] = df['X'].str.lower() # python is case sensitive thats why we are converting every thing in lower case or upper case 

In [21]:
def text_process(mess):
    """
    1. remove the punctuation 
    2. remove the stopwords
    3. return the list of clean textwords
    """
    nopunc = [char for char in mess if char not in string.punctuation]
    nopunc = "".join(nopunc)

    return[ word for word in nopunc.split() if word not in stopwords.words('english')]


In [22]:
df['X'].apply(text_process)

0       [go, jurong, point, crazy, available, bugis, n...
1                          [ok, lar, joking, wif, u, oni]
2       [free, entry, 2, wkly, comp, win, fa, cup, fin...
3           [u, dun, say, early, hor, u, c, already, say]
4       [nah, dont, think, goes, usf, lives, around, t...
                              ...                        
6771    [2nd, time, tried, 2, contact, u, u, å£750, po...
6772                   [ì, b, going, esplanade, fr, home]
6773                     [pity, mood, soany, suggestions]
6774    [guy, bitching, acted, like, id, interested, b...
6775                                   [rofl, true, name]
Name: X, Length: 6776, dtype: object

In [23]:
# now we will convert every unique word into a number

In [24]:
from sklearn.feature_extraction.text import CountVectorizer
# assign a ID/token number to each word

In [25]:
bow_transformer = CountVectorizer(analyzer=text_process).fit(df["X"])

Cell [25] (bow_transformer = ...): This does the heavy lifting for setting up the vocabulary.

It creates a CountVectorizer and tells it to use your custom text_process function as the analyzer. This means before it counts anything, it runs your punctuation-and-stopword-removal code on the text.

The .fit(df["X"]) part tells it to scan the entire 'X' column to learn the complete vocabulary (every single unique clean word used across all messages). "BOW" stands for Bag of Words.

In [26]:
len(bow_transformer.vocabulary_)

9422

In [27]:
# tdm --> term document matrix

In [28]:
print(len(bow_transformer.vocabulary_))

9422


In [29]:
tdm = bow_transformer.transform(df['X'])

Cell [29]: Converts the raw text column (df['X']) into a term-document matrix (tdm), a numerical grid where values represent word counts.

In [30]:
tdm.shape

(6776, 9422)

Cell [30]: Outputs the matrix dimensions, confirming 6,776 rows (individual text messages) and 9,422 columns (unique words).

In [31]:
type(tdm)
# this tdm will be our X used in model building 

scipy.sparse._csr.csr_matrix

In [32]:
df.head()

,Y,X
0,0,"go until jurong point, crazy.. available only ..."
1,0,ok lar... joking wif u oni...
2,1,free entry in 2 a wkly comp to win fa cup fina...
3,0,u dun say so early hor... u c already then say...
4,0,"nah i don't think he goes to usf, he lives aro..."


In [33]:
# logitic,dt,

In [34]:
from sklearn.model_selection import train_test_split
train_x, test_x, train_y, test_y = train_test_split(tdm, df.Y)

In [35]:
from sklearn.metrics import confusion_matrix, accuracy_score,recall_score,precision_score,f1_score
from sklearn.metrics import *

In [36]:
train_y = train_y.astype(int)
test_y = test_y.astype(int)

Convert target variables to integers to ensure compatibility with machine learning models

In [37]:
from sklearn.linear_model import LogisticRegression
logreg = LogisticRegression()
logreg.fit(train_x, train_y)#model build


,penalty,'l2'
,dual,False
,tol,0.0001
,C,1.0
,fit_intercept,True
,intercept_scaling,1
,class_weight,None
,random_state,None
,solver,'lbfgs'
,max_iter,100
,multi_class,'deprecated'


In [38]:
pred = logreg.predict(test_x)
print(confusion_matrix(test_y,pred))
print(classification_report(test_y, pred))

[[1447    0]
 [  26  221]]
              precision    recall  f1-score   support

           0       0.98      1.00      0.99      1447
           1       1.00      0.89      0.94       247

    accuracy                           0.98      1694
   macro avg       0.99      0.95      0.97      1694
weighted avg       0.98      0.98      0.98      1694



In [39]:
from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier()
dt.fit(train_x, train_y)
pred = dt.predict(test_x)
tab = confusion_matrix(test_y, pred)
print(tab)
print(
    accuracy_score(test_y, pred),
    " ",
    recall_score(test_y, pred),
    " ",
    precision_score(test_y, pred))

[[1431   16]
 [  31  216]]
0.9722550177095631   0.8744939271255061   0.9310344827586207


In [40]:

from  sklearn.ensemble import RandomForestClassifier
dt = RandomForestClassifier(oob_score=True)
dt.fit(train_x,train_y)
pred = dt.predict(test_x)
tab = confusion_matrix(test_y, pred)
print(tab)
print(accuracy_score(test_y, pred))

[[1447    0]
 [  36  211]]
0.9787485242030697
